version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - /home/raymond/_DATA_/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    environment:
      HOST: db
      URL_DOMAIN: $URL_DOMAIN
      SHOPIFY_API_KEY: $SHOPIFY_API_KEY
      SHOPIFY_API_SECRET: $SHOPIFY_API_SECRET
    ports:
      - "5001:3001"
    depends_on:
      - db
